# # WorkFlow
# name: Github Actions 실행시켜보기

# # 언제 해당 파일이 실행될건지
# on:
#   push:
#     branches:
#       - main # main branch가 변경 됐을 때

# # WorkFlow는 여러개의 Job으로 이루어질 수 있고
# jobs:
#   My-Deploy-Job:
#     runs-on: ubuntu-latest # 운영체제를 선택하는 구문. ubuntu도 운영체제 중 하나 (window 같은 거)

#     # 하나의 Job은 여러개의 tep으로 이루어져있다.
#     steps:
#       - name: Hello World 출력하기 # steps 이름 지정 (이건 쉽게 알아보려고)
#         run: echo "Hello World" # 명령어 실행 (리눅스 문법)

#       - name: 여러 명령어 문장 작성하기
#         run: | # 해당 기호는 여러 명령어를 실행하겠다를 선언하는 것
#           echo "Good"
#           echo "Morning"
#           pwd
      
#       - name: Github Actions 자체 저장되어 있는 변수 사용해보기
#         run: |
#           echo $GITHUB_REPOSITORY
#           echo $GITHUB_SHA

#       - name: Github Actions 자체 시크릿 변수 사용해보기
#         # github 해당 레포지토리의 설정에서 Actions secrets and variables의 actions에서 변수설정을 할 수 있으며,
#         # 이름 그대로 비밀이기 때문에 echo를 입력해도 ***로 표시될 뿐 볼 수 없다 (빈 공백만 아니면 잘 출력된 것)
#         run: | 
#           echo ${{ secrets.MY_NAME }}
#           echo ${{ secrets.MY_HOBBY }}

name: Deploy To S3 And Invalidate CludFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Repository 파일 출력하기
        run: ls